main: io.github.lasercar.simplemention.SimpleMention
author: Jon (lasercar.github.io)
website: https://github.com/lasercar/SimpleMention
name: SimpleMention
version: 0.0.2
description: "@Mention, with nickname, ping, and multiple mention support"
